#!/bin/bash

bash push-stream2fa-image.sh

sudo cat $TOKEN_PATH | docker login -u tuttlsj1 --password-stdin
docker pull tuttlsj1/cs4287:stream2fa
docker logout

docker rm -f stream2fa-api

docker-compose up --detach --no-recreate

