#!/bin/sh

sudo cat $TOKEN_PATH | docker login -u tuttlsj1 --password-stdin
docker pull tuttlsj1/cs4287:stream2fa
docker logout

docker rm -f stream2fa-server 2> /dev/null

docker compose up --build --detach --no-recreate

